---
version: '3'
services:
 web:
  image: nginx:alpine
  ports:
   - "8080:80"
  volumes:
   - ./site.conf:/etc/nginx/conf.d/default.conf
   - data-volume:/usr/share/nginx/html:ro
  links:
   - php
 php:
  image: php7:latest
  ports:
   - "9000:9000"
  volumes:
   - data-volume:/usr/share/nginx/html
 db:
  image: mysql:latest
  volumes:
   - data-volume-db:/var/lib/mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: 1234567
 phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  links:
   - db
  ports:
   - "8181:80"
  environment:
   MYSQL_USERNAME: root
   MYSQL_ROOT_PASSWORD: 1234567
volumes:
 data-volume:
 data-volume-db: